name: Spring 
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    run-on: windows-latest
    steps:
      - name: checkout source
        uses: action.checkout@v3
        
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
           java-version: '17'
           distribution: 'temurin'
           
      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test
      
